### ISSUE TITLE
Peer review by Kedir Hussen Hamza

### ISSUE THREAD

**Issue by kedham** [teokem/project-work-2020-katrinros#1]
Hi Katrin,
It looks nice work and thank you for introducing us to the science of planet formation and planet-forming materials. 
Here I put my comments based on the project requirement from the course.
    **Documentation:**
        - The title of the project is clearly stated, but the abstract, with its current status, I would say it looks more of a summary. 
        - There are clear instructions on how to run the notebook. I was able to redo the steps provided in the notebook.
       - The required packages are also included in the environment.yml file
       - A brief explanation of the reason each package/library was used included in the code using the hash symbol('#'). Markdown was used to explain each step. Equations, tables, links, images, or videos were not used in this notebook.
        
    **Input/Output:**
        - Numpy, scipy, matplotlib,  and matplotlib.pyplot packages were used for manipulating and plotting the data. But I haven't seen pandas. If possible, it might be good to show the use of pandas.
    **Data visualization:**
        - Publication-ready quality figures were shown in the notebook and it meets the editorial guide of Graphical Excellence.
            
    **Version control, sharing, and archiving:**
        I haven't seen any digital object identifier (DOI) for this file.

**Comment by katrinros** [comment]
Dear Kedir,

Thank you very much for taking the time to review my project. I have now updated it according to your suggestions, I specify the updates below:

- I have updated the abstract to read less like a summary, and I instead moved the scientific summary to after the abstract.

- Input/output: I am now using panda DataFrames to save the manipulated data, and to export the data to disc. For input I still use scipy as my input data is from IDL and I have not found a way to import this type of data using pandas.

- DOI: I have now added a DOI for my project.

Thanks again for your review,
Katrin
