### ISSUE TITLE
peer review by Saeid

### ISSUE THREAD

**Issue by saeidpiraniGitHub** [teokem/project-work-2020-katrinros#2]
Dear Karin

First of all, my apology for late peer review.
Thanks for the well arranged project, everything is properly done, except application of pandas library for data read and manipulation.

Best
Saeid

 1. Documentation:
- includes rich documentation using Markdown (equations, tables, links, images or videos)
**properly done**

- includes instructions on how to run the notebook
**properly done**

-  includes the required packages in an environment.yml 
**properly done**

- file  is reproducible, i.e., someone else should be able to redo the steps 
**properly done**

1. Input/Output:
- uses pandas to read large data sets or numpy to load data from text files
**scipy is applied for reading data sets,instead of pandas and numpy**

- uses pandas to save to disk the processed or generated data
**There is no application from pandas library**
 
1. Scientific computing/data processing:
- performs numerical operations (numpy, scipy, pandas) or manipulates, groups, and aggregates a data set (pandas)
**Pandas library is not applied for read, save and data manipulation**

 **Data visualization:**
-  includes at least one composite plot (inset or multiple panels)
**properly done**

- the axes are labeled, the font sizes are sufficiently large, the figures are saved as rasterized images (300 dpi) or vector art
**properly done**

 **Version control, sharing, and archiving:**
- is archived in a repository with a digital object identifier (DOI)
**I didn't find out DOI for your project**

**Comment by katrinros** [comment]
Dear Saeid,

Thank you very much for taking the time to review my project. I have now updated it according to your suggestions, I specify the updates below:

- Input/output: I am now using panda DataFrames to save the manipulated data, and to export the data to disc. For input I still use scipy as my input data is from IDL and I have not found a way to import this type of data using pandas.

- DOI: I have now added a DOI for my project.

Thanks again for your review,
Katrin
